---
title: 'Wrapping up'
teaching: 10
exercises: 0
---


::::::::::::::::::::::::::::::::::::::::::::::: instructor

If you have spare time, you may want to share the 'culture' page that's in the instructor menu. Consider your audience - this may be less relevant to an audience of students and ECR's, however your more senior academics and leaders may find the content thought-provoking.

:::::::::::::::::::::::::::::::::::::::::::::::

## Where to from here?

::::::::::::::::::::::::::::::::::::::::::::::: instructor

A place to share what is happening at your own institutes, and where attendees can get support.


:::::::::::::::::::::::::::::::::::::::::::::::

```{r child="files/whereToFromHere.Rmd"}
```


For each of our 7 lessons, do we have an action item?

Let’s establish concrete action items for the upcoming week or two based on the tasks we’ve just documented.

::::::::::::::::::::::::::::::::::::::::::::::: challenge

***Take this time to do one of the following:***

Email yourself a website you've found today to read through later.

Set a calendar entry to dedicate some time to complete a task.

Pair with someone here to encourage each other.

Talk to your colleagues about a suggestedchange to make in your project.

:::::::::::::::::::::::::::::::::::::::::::::::

Even by only taking small steps, you are now further down the reproducible research path.


## This lesson website

These lessons will stay available for you to refer to going into the future. You are welcome to pass on any feedback to your trainer, as we aim to continuously improve our lessons.




